### PR TITLE
French translation reworked

### PR DESCRIPTION
**Pull request by simonporte**
Reworked from scratch because of a lot of mistakes and untranslated strings.

Changed a sentence in English.
Tray bar is not a common name and it can be confused with task bar.
If you don't like it, it can also be called system tray instead of notification area.

I can squash my commits if you prefer.

### CODE REVIEW

**Comment by simonporte** [comment]
Hello,

The checks fail.
I wondered if it was because of characters used in french.
So I escaped `'` as `\'`, but there were already `'` in the previous translation.
I don't think it is because of accent letters `éàôè` because there is accents in other languages files.
I let my commit as is with escaped `\'` for now.
If you can point me in the right direction to correct things.

Thanks.

I also dropped the commit for english text for now, i'll write it here :

Change
`"CloseToTray": "Close application to tray bar",`
To
`"CloseToTray": "Close application to notification area",`

**Comment by csutorasa** [comment]
I will check what is going on. By the way the 4.x version is getting prepared so I can still merge this, but probably I will need new translations for 4.x versions.

**Comment by simonporte** [comment]
Thanks.
If you can merge, I will update when the next release is published if needed.
The text is expected to change a lot?
New files language files are not yet available ?

**Comment by csutorasa** [comment]
Merged to 3.x as 8350f905b1260043e5fd6aa60e667244ab04d52a

**Pull request closed without merging**
